apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-js-project
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: rodrigocasio/guestbook-js:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master"
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"
